In [150]:
#Using linear regression to predict the house pricing.At the same time, the price is divided into cheap, general, and expensive. The price tag is classified by machine learning.

In [138]:

##import the data and package
import numpy as np
import pandas as pd
import math
from scipy.stats import pearsonr

data = pd.read_csv('kc_house_data.csv')

In [139]:
#overview the data to check if there are outlier 
data.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [140]:
#check the missing value
data.isnull().sum()
#if there are some missing value 
# df = df.dropna(how='any')

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [141]:
#caculate the correlation value between the feature and the target and do the feature selection for linear model
features = data.iloc[:,3:].columns.tolist()
target = data.iloc[:,2].name
correlations = {}
for f in features:
    data_temp = data[[f,target]]
    x1 = data_temp[f].values
    x2 = data_temp[target].values
    key = f + ' vs ' + target
    correlations[key] = pearsonr(x1,x2)[0]
    data_correlations = pd.DataFrame(correlations, index=['Value']).T
data_correlations.loc[data_correlations['Value'].abs().sort_values(ascending=False).index]

                           Value
sqft_living vs price    0.702035
grade vs price          0.667434
sqft_above vs price     0.605567
sqft_living15 vs price  0.585379
bathrooms vs price      0.525138
view vs price           0.397293
sqft_basement vs price  0.323816
bedrooms vs price       0.308350
lat vs price            0.307003
waterfront vs price     0.266369
floors vs price         0.256794
yr_renovated vs price   0.126434
sqft_lot vs price       0.089661
sqft_lot15 vs price     0.082447
yr_built vs price       0.054012
zipcode vs price       -0.053203
condition vs price      0.036362
long vs price           0.021626

In [142]:
from sklearn import linear_model


regr = linear_model.LinearRegression()
new_data = data[['sqft_living','grade', 'sqft_above', 'sqft_living15','bathrooms','view','sqft_basement','lat','waterfront','yr_built','bedrooms','lat','floors','waterfront']]

In [143]:
X = new_data.values
y = data.price.values

array([[1.18000e+03, 7.00000e+00, 1.18000e+03, ..., 4.75112e+01,
        1.00000e+00, 0.00000e+00],
       [2.57000e+03, 7.00000e+00, 2.17000e+03, ..., 4.77210e+01,
        2.00000e+00, 0.00000e+00],
       [7.70000e+02, 6.00000e+00, 7.70000e+02, ..., 4.77379e+01,
        1.00000e+00, 0.00000e+00],
       ...,
       [1.02000e+03, 7.00000e+00, 1.02000e+03, ..., 4.75944e+01,
        2.00000e+00, 0.00000e+00],
       [1.60000e+03, 8.00000e+00, 1.60000e+03, ..., 4.75345e+01,
        2.00000e+00, 0.00000e+00],
       [1.02000e+03, 7.00000e+00, 1.02000e+03, ..., 4.75941e+01,
        2.00000e+00, 0.00000e+00]])

In [144]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y ,test_size=0.2)

In [145]:
regr.fit(X_train, y_train)
print(regr.predict(X_test))

[ 586830.41382763  400408.99695658  500763.0559124  ...  614704.07057385
 1288201.89826359  258085.73339681]

In [146]:
regr.score(X_test, y_test)

0.6876232964978477

In [134]:
# Calculate the Root Mean Squared Error
print("RMSE: %.2f"
      % math.sqrt(np.mean((regr.predict(X_test) - y_test) ** 2)))

RMSE: 205770.08

In [173]:
df=pd.read_csv('kc_house_data.csv',nrows=100)

In [174]:
#encoding the price and divide it into three lable cheap, general, expensive
df['price_level']=pd.cut((df['price'].values),3, labels=[" cheap", "general", "expensive"])

In [175]:
target = 'price_level'

In [176]:
#drop the column that is meaningless

X = df.drop(columns=[target,'price','id','date'])
y = df[target]

In [177]:
#check the categorical variable
for j in range(X.shape[1]):
    print(X.columns[j] + ':')
    print(X.iloc[:, j].value_counts(), end='\n\n')

bedrooms:
3    52
4    29
5    10
2     9
Name: bedrooms, dtype: int64

bathrooms:
2.50    24
1.00    22
1.75    16
2.25    10
1.50     8
2.00     7
2.75     5
3.25     3
3.00     3
4.00     1
4.50     1
Name: bathrooms, dtype: int64

sqft_living:
2570    3
1410    2
1890    2
1810    2
1680    2
1960    2
2770    2
1200    2
1260    2
1250    2
1160    2
1190    2
1580    2
2450    2
2320    2
1980    2
1660    2
1000    1
2730    1
1790    1
5420    1
2350    1
1060    1
3250    1
1715    1
1030    1
1070    1
1180    1
1570    1
3300    1
       ..
3560    1
990     1
3050    1
4220    1
1520    1
2290    1
1780    1
1400    1
1900    1
3450    1
2270    1
2140    1
2620    1
1370    1
2300    1
2750    1
1600    1
2753    1
1090    1
1220    1
2250    1
2380    1
3150    1
2660    1
1710    1
1620    1
2519    1
3160    1
2240    1
1280    1
Name: sqft_living, Length: 82, dtype: int64

sqft_lot:
5000      7
6000      4
5060      2
8400      2
35102     1
6560      1
8690      1
6819      1
34848     1
12070     1
6278      1
4648      1
7807      1
6300      1
101930    1
9643      1
1581      1
7470      1
9656      1
7403      1
9134      1
13416     1
2040      1
11049     1
3600      1
24186     1
19901     1
7553      1
8080      1
7300      1
         ..
50529     1
5520      1
9976      1
9199      1
9850      1
8528      1
39683     1
6500      1
3809      1
36847     1
4300      1
15681     1
50094     1
44867     1
9796      1
41800     1
5612      1
7242      1
5963      1
9680      1
13603     1
6353      1
3060      1
1066      1
6634      1
14040     1
4697      1
10250     1
6659      1
6400      1
Name: sqft_lot, Length: 89, dtype: int64

floors:
1.0    49
2.0    37
1.5    12
3.0     2
Name: floors, dtype: int64

waterfront:
0    99
1     1
Name: waterfront, dtype: int64

view:
0    94
4     2
3     2
2     2
Name: view, dtype: int64

condition:
3    62
4    26
5    10
2     1
1     1
Name: condition, dtype: int64

grade:
7     50
8     28
9     10
6      5
10     4
11     2
5      1
Name: grade, dtype: int64

sqft_above:
1980    3
1090    2
2390    2
860     2
1890    2
1000    2
1190    2
1510    2
1680    2
2250    2
1260    2
1250    2
2570    2
1900    2
1290    2
1200    2
2320    2
1600    2
990     2
1050    2
2600    1
1070    1
2350    1
960     1
1180    1
1060    1
930     1
2720    1
3890    1
1810    1
       ..
2170    1
1400    1
1570    1
3450    1
2165    1
2290    1
880     1
3520    1
1770    1
790     1
1640    1
2660    1
2620    1
2270    1
2360    1
1960    1
1370    1
2240    1
3160    1
2519    1
1750    1
1710    1
2130    1
2380    1
3250    1
1860    1
765     1
1850    1
890     1
1280    1
Name: sqft_above, Length: 79, dtype: int64

sqft_basement:
0       59
730      3
910      2
790      2
290      2
1700     2
600      2
700      2
500      2
990      1
1000     1
265      1
780      1
240      1
400      1
1040     1
1010     1
410      1
880      1
360      1
550      1
1510     1
300      1
560      1
820      1
760      1
1600     1
330      1
970      1
588      1
720      1
1620     1
1530     1
Name: sqft_basement, dtype: int64

yr_built:
2003    5
1965    4
2005    4
1981    3
1979    3
1968    3
1995    3
1955    2
1973    2
1966    2
1959    2
1956    2
1916    2
1985    2
1948    2
1941    2
1939    2
1933    2
1929    2
1927    2
1925    2
1953    2
1969    2
2001    2
2014    2
2006    2
1992    2
1984    1
1946    1
1952    1
       ..
2002    1
1947    1
1942    1
2000    1
2008    1
1930    1
1900    1
1904    1
1909    1
1922    1
1954    1
1996    1
1986    1
1994    1
1980    1
1987    1
1977    1
1975    1
1988    1
1972    1
1915    1
1989    1
1967    1
1991    1
1964    1
1963    1
1962    1
1961    1
1960    1
1921    1
Name: yr_built, Length: 62, dtype: int64

yr_renovated:
0       97
1991     2
2002     1
Name: yr_renovated, dtype: int64

zipcode:
98117    6
98115    5
98038    5
98056    4
98042    4
98023    4
98074    3
98125    3
98133    3
98119    3
98166    3
98007    2
98092    2
98001    2
98002    2
98003    2
98004    2
98136    2
98107    2
98105    2
98059    2
98019    2
98148    2
98058    2
98028    2
98030    2
98053    2
98052    2
98008    2
98040    2
98199    1
98198    1
98075    1
98103    1
98045    1
98126    1
98112    1
98116    1
98118    1
98005    1
98122    1
98010    1
98144    1
98146    1
98070    1
98027    1
98032    1
98034    1
98178    1
Name: zipcode, dtype: int64

lat:
47.7073    2
47.6870    2
47.3663    2
47.7274    1
47.6113    1
47.6571    1
47.5474    1
47.6034    1
47.3343    1
47.4934    1
47.4095    1
47.6506    1
47.6525    1
47.4366    1
47.3739    1
47.6827    1
47.6648    1
47.3266    1
47.7168    1
47.6796    1
47.3512    1
47.5112    1
47.6889    1
47.3533    1
47.3608    1
47.3341    1
47.6194    1
47.6848    1
47.2897    1
47.5880    1
          ..
47.4041    1
47.6007    1
47.4485    1
47.5873    1
47.5714    1
47.6823    1
47.6621    1
47.6145    1
47.5228    1
47.4258    1
47.3684    1
47.7362    1
47.3576    1
47.2909    1
47.7379    1
47.4428    1
47.4811    1
47.3097    1
47.3420    1
47.4276    1
47.7558    1
47.6950    1
47.7025    1
47.5636    1
47.4109    1
47.5316    1
47.5822    1
47.3089    1
47.7277    1
47.6702    1
Name: lat, Length: 97, dtype: int64

long:
-122.375    2
-122.110    2
-122.304    2
-122.257    2
-122.310    2
-122.386    2
-122.189    2
-122.045    2
-122.149    2
-122.031    2
-122.233    2
-122.394    2
-122.362    1
-122.365    1
-122.368    1
-122.180    1
-121.987    1
-122.249    1
-122.070    1
-122.175    1
-122.347    1
-122.125    1
-122.391    1
-122.341    1
-122.218    1
-122.343    1
-122.322    1
-122.384    1
-122.116    1
-122.157    1
           ..
-122.393    1
-122.036    1
-122.357    1
-122.369    1
-122.320    1
-122.281    1
-122.290    1
-122.166    1
-121.958    1
-122.229    1
-122.151    1
-122.387    1
-122.327    1
-122.292    1
-122.335    1
-122.073    1
-122.287    1
-122.145    1
-121.714    1
-122.344    1
-122.315    1
-122.025    1
-122.291    1
-122.122    1
-122.008    1
-122.179    1
-122.339    1
-122.451    1
-122.360    1
-122.194    1
Name: long, Length: 88, dtype: int64

sqft_living15:
1570    4
1950    3
1590    2
1440    2
1360    2
2020    2
1580    2
1290    2
1340    2
2680    2
1030    2
1780    2
1650    2
3530    1
2210    1
2350    1
2221    1
1460    1
2730    1
3625    1
1720    1
3240    1
1850    1
2470    1
1060    1
1330    1
2160    1
2720    1
2570    1
1410    1
       ..
1940    1
2410    1
1750    1
2200    1
1900    1
1390    1
1520    1
970     1
2550    1
1400    1
1350    1
2270    1
2500    1
2140    1
890     1
2690    1
1220    1
2630    1
1130    1
1480    1
1610    1
1190    1
1228    1
1870    1
1980    1
2390    1
2520    1
1160    1
1370    1
1280    1
Name: sqft_living15, Length: 84, dtype: int64

sqft_lot15:
5000      4
4500      3
6000      2
4080      2
4000      2
4745      1
6819      1
11044     1
5669      1
11049     1
101930    1
9133      1
8750      1
7807      1
8113      1
7349      1
7570      1
3090      1
7500      1
8840      1
5693      1
20158     1
3264      1
72513     1
15616     1
6045      1
4557      1
4750      1
10500     1
38917     1
         ..
3573      1
18900     1
7800      1
35065     1
7203      1
13685     1
4800      1
4705      1
10208     1
20336     1
6738      1
6400      1
8386      1
4300      1
11467     1
12635     1
7503      1
2640      1
6865      1
2025      1
8542      1
30617     1
8850      1
7510      1
7639      1
5080      1
6235      1
1756      1
8925      1
5639      1
Name: sqft_lot15, Length: 92, dtype: int64

In [178]:
import pandas as pd

# Implement me
X = pd.get_dummies(X, columns=X.columns)
X.head()

,bedrooms_2,bedrooms_3,bedrooms_4,bedrooms_5,bathrooms_1.0,bathrooms_1.5,bathrooms_1.75,bathrooms_2.0,bathrooms_2.25,bathrooms_2.5,...,sqft_lot15_20336,sqft_lot15_30617,sqft_lot15_35020,sqft_lot15_35065,sqft_lot15_38917,sqft_lot15_39750,sqft_lot15_50529,sqft_lot15_72513,sqft_lot15_101930,sqft_lot15_135036
0,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [179]:
y.value_counts()

 cheap       83
general      16
expensive     1
Name: price_level, dtype: int64

In [180]:
from sklearn.preprocessing import LabelEncoder

# Implement me
le = LabelEncoder()
y = le.fit_transform(y)

pd.DataFrame(data=y, columns=[target])[target].value_counts()

0    83
2    16
1     1
Name: price_level, dtype: int64

In [181]:
from imblearn.over_sampling import RandomOverSampler

# RandomOverSampler (with random_state=0)
# Implement me
ros = RandomOverSampler(random_state=0)
X, y = ros.fit_sample(X, y)

pd.DataFrame(data=y, columns=[target])[target].value_counts()

2    83
1    83
0    83
Name: price_level, dtype: int64

In [182]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

clfs = {'lr': LogisticRegression(random_state=0),
        'mlp': MLPClassifier(random_state=0),
        'dt': DecisionTreeClassifier(random_state=0),
        'rf': RandomForestClassifier(random_state=0),
        'svc': SVC(random_state=0),
        'knn': KNeighborsClassifier(),
        'gnb': GaussianNB()}

In [183]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

pipe_clfs = {}

for name, clf in clfs.items():
    # Implement me
    pipe_clfs[name] = Pipeline([('StandardScaler', StandardScaler()), ('clf', clf)])

In [184]:
param_grids = {}

In [185]:
C_range = [10 ** i for i in range(-4, 5)]

param_grid = [{'clf__multi_class': ['ovr'], 
               'clf__solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
               'clf__C': C_range},
              
              {'clf__multi_class': ['multinomial'],
               'clf__solver': ['newton-cg', 'lbfgs', 'sag', 'saga'],
               'clf__C': C_range}]

# Implement me
param_grids['lr'] = param_grid

In [186]:
param_grid = [{'clf__hidden_layer_sizes': [10, 100, 200],
               'clf__activation': ['identity', 'logistic', 'tanh', 'relu']}]

# Implement me
param_grids['mlp'] = param_grid

In [187]:
param_grid = [{'clf__min_samples_split': [2, 10, 30],
               'clf__min_samples_leaf': [1, 10, 30]}]

# Implement me
param_grids['dt'] = param_grid

In [188]:
param_grid = [{'clf__n_estimators': [2, 10, 30],
               'clf__min_samples_split': [2, 10, 30],
               'clf__min_samples_leaf': [1, 10, 30]}]

# Implement me
param_grids['rf'] = param_grid

In [189]:
param_grid = [{'clf__C': [0.01, 0.1, 1, 10, 100],
               'clf__gamma': ['auto', 'scale'],
               'clf__kernel': ['linear', 'poly', 'rbf', 'sigmoid']}]

# Implement me
param_grids['svc'] = param_grid

In [190]:
param_grid = [{'clf__n_neighbors': list(range(1, 11))}]

# Implement me
param_grids['knn'] = param_grid

In [191]:
param_grid = [{'clf__var_smoothing': [10 ** i for i in range(-10, -7)]}]

# Implement me
param_grids['gnb'] = param_grid

In [192]:
import warnings
warnings.filterwarnings('ignore')

In [193]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

# The list of [best_score_, best_params_, best_estimator_]
best_score_param_estimators = []

# For each classifier
for name in pipe_clfs.keys():
    # GridSearchCV
    # Implement me
    gs = GridSearchCV(estimator=pipe_clfs[name],
                      param_grid=param_grids[name],
                      scoring='accuracy',
                      n_jobs=-1,
                      cv=StratifiedKFold(n_splits=10,
                                         shuffle=True,
                                         random_state=0))
    # Fit the pipeline
    # Implement me
    gs = gs.fit(X, y)
    
    # Update best_score_param_estimators
    best_score_param_estimators.append([gs.best_score_, gs.best_params_, gs.best_estimator_])

In [93]:
# Sort best_score_param_estimators in descending order of the best_score_
# Implement me
best_score_param_estimators = sorted(best_score_param_estimators, key=lambda x : x[0], reverse=True)

# For each [best_score_, best_params_, best_estimator_]
for best_score_param_estimator in best_score_param_estimators:
    # Print out [best_score_, best_params_, best_estimator_], where best_estimator_ is a pipeline
    # Since we only print out the type of classifier of the pipeline
    print([best_score_param_estimator[0], best_score_param_estimator[1], type(best_score_param_estimator[2].named_steps['clf'])], end='\n\n')

[0.9959839357429718, {'clf__min_samples_leaf': 1, 'clf__min_samples_split': 2, 'clf__n_estimators': 30}, <class 'sklearn.ensemble.forest.RandomForestClassifier'>]

[0.9959839357429718, {'clf__C': 1, 'clf__gamma': 'auto', 'clf__kernel': 'sigmoid'}, <class 'sklearn.svm.classes.SVC'>]

[0.9879518072289156, {'clf__C': 10, 'clf__multi_class': 'multinomial', 'clf__solver': 'sag'}, <class 'sklearn.linear_model.logistic.LogisticRegression'>]

[0.9839357429718876, {'clf__var_smoothing': 1e-10}, <class 'sklearn.naive_bayes.GaussianNB'>]

[0.9718875502008032, {'clf__activation': 'relu', 'clf__hidden_layer_sizes': 100}, <class 'sklearn.neural_network.multilayer_perceptron.MLPClassifier'>]

[0.9477911646586346, {'clf__min_samples_leaf': 1, 'clf__min_samples_split': 2}, <class 'sklearn.tree.tree.DecisionTreeClassifier'>]

[0.6746987951807228, {'clf__n_neighbors': 1}, <class 'sklearn.neighbors.classification.KNeighborsClassifier'>]

In [194]:
data

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,...,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
10,1736800520,20150403T000000,662500.0,3,2.50,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
11,9212900260,20140527T000000,468000.0,2,1.00,1160,6000,1.0,0,0,...,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
12,114101516,20140528T000000,310000.0,3,1.00,1430,19901,1.5,0,0,...,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
13,6054650070,20141007T000000,400000.0,3,1.75,1370,9680,1.0,0,0,...,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
14,1175000570,20150312T000000,530000.0,5,2.00,1810,4850,1.5,0,0,...,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850
15,9297300055,20150124T000000,650000.0,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
16,1875500060,20140731T000000,395000.0,3,2.00,1890,14040,2.0,0,0,...,7,1890,0,1994,0,98019,47.7277,-121.962,1890,14018
17,6865200140,20140529T000000,485000.0,4,1.00,1600,4300,1.5,0,0,...,7,1600,0,1916,0,98103,47.6648,-122.343,1610,4300
18,16000397,20141205T000000,189000.0,2,1.00,1200,9850,1.0,0,0,...,7,1200,0,1921,0,98002,47.3089,-122.210,1060,5095
19,7983200060,20150424T000000,230000.0,3,1.00,1250,9774,1.0,0,0,...,7,1250,0,1969,0,98003,47.3343,-122.306,1280,8850
20,6300500875,20140514T000000,385000.0,4,1.75,1620,4980,1.0,0,0,...,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
21,2524049179,20140826T000000,2000000.0,3,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
22,7137970340,20140703T000000,285000.0,5,2.50,2270,6300,2.0,0,0,...,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
23,8091400200,20140516T000000,252700.0,2,1.50,1070,9643,1.0,0,0,...,7,1070,0,1985,0,98030,47.3533,-122.166,1220,8386
24,3814700200,20141120T000000,329000.0,3,2.25,2450,6500,2.0,0,0,...,8,2450,0,1985,0,98030,47.3739,-122.172,2200,6865
25,1202000200,20141103T000000,233000.0,3,2.00,1710,4697,1.5,0,0,...,6,1710,0,1941,0,98002,47.3048,-122.218,1030,4705
26,1794500383,20140626T000000,937000.0,3,1.75,2450,2691,2.0,0,0,...,8,1750,700,1915,0,98119,47.6386,-122.360,1760,3573
27,3303700376,20141201T000000,667000.0,3,1.00,1400,1581,1.5,0,0,...,8,1400,0,1909,0,98112,47.6221,-122.314,1860,3861
28,5101402488,20140624T000000,438000.0,3,1.75,1520,6380,1.0,0,0,...,7,790,730,1948,0,98115,47.6950,-122.304,1520,6235
29,1873100390,20150302T000000,719000.0,4,2.50,2570,7173,2.0,0,0,...,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21583,2025049203,20140610T000000,399950.0,2,1.00,710,1157,2.0,0,0,...,7,710,0,1943,0,98102,47.6413,-122.329,1370,1173
21584,952006823,20141202T000000,380000.0,3,2.50,1260,900,2.0,0,0,...,7,940,320,2007,0,98116,47.5621,-122.384,1310,1415
21585,3832050760,20140828T000000,270000.0,3,2.50,1870,5000,2.0,0,0,...,7,1870,0,2009,0,98042,47.3339,-122.055,2170,5399
21586,2767604724,20141015T000000,505000.0,2,2.50,1430,1201,3.0,0,0,...,8,1430,0,2009,0,98107,47.6707,-122.381,1430,1249
21587,6632300207,20150305T000000,385000.0,3,2.50,1520,1488,3.0,0,0,...,8,1520,0,2006,0,98125,47.7337,-122.309,1520,1497
21588,2767600688,20141113T000000,414500.0,2,1.50,1210,1278,2.0,0,0,...,8,1020,190,2007,0,98117,47.6756,-122.375,1210,1118
21589,7570050450,20140910T000000,347500.0,3,2.50,2540,4760,2.0,0,0,...,8,2540,0,2010,0,98038,47.3452,-122.022,2540,4571
21590,7430200100,20140514T000000,1222500.0,4,3.50,4910,9444,1.5,0,0,...,11,3110,1800,2007,0,98074,47.6502,-122.066,4560,11063
21591,4140940150,20141002T000000,572000.0,4,2.75,2770,3852,2.0,0,0,...,8,2770,0,2014,0,98178,47.5001,-122.232,1810,5641
21592,1931300412,20150416T000000,475000.0,3,2.25,1190,1200,3.0,0,0,...,8,1190,0,2008,0,98103,47.6542,-122.346,1180,1224
21593,8672200110,20150317T000000,1088000.0,5,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21594,5087900040,20141017T000000,350000.0,4,2.75,2500,5995,2.0,0,0,...,8,2500,0,2008,0,98042,47.3749,-122.107,2530,5988
21595,1972201967,20141031T000000,520000.0,2,2.25,1530,981,3.0,0,0,...,8,1480,50,2006,0,98103,47.6533,-122.346,1530,1282
21596,7502800100,20140813T000000,679950.0,5,2.75,3600,9437,2.0,0,0,...,9,3600,0,2014,0,98059,47.4822,-122.131,3550,9421
21597,191100405,20150421T000000,1575000.0,4,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125
21598,8956200760,20141013T000000,541800.0,4,2.50,3118,7866,2.0,0,2,...,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500
21599,7202300110,20140915T000000,810000.0,4,3.00,3990,7838,2.0,0,0,...,9,3990,0,2003,0,98053,47.6857,-122.046,3370,6814
21600,249000205,20141015T000000,1537000.0,5,3.75,4470,8088,2.0,0,0,...,11,4470,0,2008,0,98004,47.6321,-122.200,2780,8964
21601,5100403806,20150407T000000,467000.0,3,2.50,1425,1179,3.0,0,0,...,8,1425,0,2008,0,98125,47.6963,-122.318,1285,1253
21602,844000965,20140626T000000,224000.0,3,1.75,1500,11968,1.0,0,0,...,6,1500,0,2014,0,98010,47.3095,-122.002,1320,11303
21603,7852140040,20140825T000000,507250.0,3,2.50,2270,5536,2.0,0,0,...,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,9834201367,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,...,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,3448900210,20141014T000000,610685.0,4,2.50,2520,6023,2.0,0,0,...,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1007500.0,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,2997800021,20150219T000000,475000.0,3,2.50,1310,1294,2.0,0,0,...,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357